site_name: Circuit Stash

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/slanda156/CircuitStash
repo_name: slanda156/CircuitStash

nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
